---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: testA
  labels:
    app: testA
spec:
  replicas: 1
  selector:
    matchLabels:
      app: testA
  template:
    metadata:
      labels:
        app: testA
    spec:
      containers:
        - name: testA
          image: username/testA:latest
          ports:
            - containerPort: 8080
          readinessProbe:
            httpGet:
              path: '/actuator/health'
              port: 8080
            initialDelaySeconds: 10
            timeoutSeconds: 2
            periodSeconds: 5
            failureThreshold: 10
          livenessProbe:
            httpGet:
              path: '/actuator/health'
              port: 8080
            initialDelaySeconds: 120
            timeoutSeconds: 2
            periodSeconds: 5
            failureThreshold: 5

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: testB
  labels:
    app: testB
spec:
  replicas: 1
  selector:
    matchLabels:
      app: testB
  template:
    metadata:
      labels:
        app: testB
    spec:
      containers:
        - name: testB
          image: username/testB:latest
          ports:
            - containerPort: 8080
          readinessProbe:
            httpGet:
              path: '/actuator/health'
              port: 8080
            initialDelaySeconds: 10
            timeoutSeconds: 2
            periodSeconds: 5
            failureThreshold: 10
          livenessProbe:
            httpGet:
              path: '/actuator/health'
              port: 8080
            initialDelaySeconds: 120
            timeoutSeconds: 2
            periodSeconds: 5
            failureThreshold: 5


---


apiVersion: v1
kind: Service
metadata:
  name: testA
  labels:
    app: testA
spec:
  ports:
    - port: 8080
      targetPort: 8080
  selector:
    app: testA


---


apiVersion: v1
kind: Service
metadata:
  name: testB
  labels:
    app: testB
spec:
  ports:
    - port: 8080
      targetPort: 8080
  selector:
    app: testB

